git:(master) ✗ ./run_kubernetes.sh
Error from server (AlreadyExists): pods "python-flask-ml" already exists
NAME              READY   STATUS    RESTARTS   AGE
python-flask-ml   1/1     Running   0          69s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000

git:(master) ✗ kubectl logs python-flask-ml
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 223-103-981
[2020-08-14 09:25:54,752] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2020-08-14 09:25:54,772] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2020-08-14 09:25:54,785] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2020-08-14 09:25:54,790] INFO in app: prediction: [20.35373177134412]
127.0.0.1 - - [14/Aug/2020 09:25:54] "POST /predict HTTP/1.1" 200 -